apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kb-assistant
resources:
  - namespace.yaml
  - postgres.yaml
  - embedder.yaml
  - index.yaml
  - doc.yaml
  - ai.yaml
  - gateway.yaml
