apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb-doc-service
spec:
  template:
    spec:
      containers:
        - name: kb-doc-service
          env:
            - name: KB_OCR_URL
              value: http://kb-ocr-service:8070
